exports.up = async function (knex) {
  await knex("funcionario").insert([
    {
      nome: "Márcio",
      usuario: "marcio",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "marcio@email.com",
      telefone: "(63) 94568-9636",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
      saldo_horas: 10,
    },
    {
      nome: "Pedro",
      usuario: "pedro",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "pedro@email.com",
      telefone: "(44) 96475-8202",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Flávio",
      usuario: "flavio",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "flavio@email.com",
      telefone: "(59) 92321-2894",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Osvaldo",
      usuario: "osvaldo",
      admin: true,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "osvaldo@email.com",
      telefone: "(12) 95503-0999",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Luís",
      usuario: "luis",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "luis@email.com",
      telefone: "(68) 94672-2488",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Emanuel",
      usuario: "emanuel",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "emanuel@email.com",
      telefone: "(58) 99523-9914",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Sandro",
      usuario: "sandro",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "sandro@email.com",
      telefone: "(10) 90849-7167",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Carlos",
      usuario: "carlos",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "carlos@email.com",
      telefone: "(48) 98887-9554",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Saulo",
      usuario: "saulo",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "saulo@email.com",
      telefone: "(81) 92105-5425",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Ricardo",
      usuario: "ricardo",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "ricardo@email.com",
      telefone: "(65) 98976-7989",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Eduardo",
      usuario: "eduardo",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "eduardo@email.com",
      telefone: "(85) 92727-0089",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
    {
      nome: "Alessandro",
      usuario: "alessandro",
      admin: false,
      cargo: "Desenvolvedor",
      setor: "Desenvolvimento",
      email: "alessandro@email.com",
      telefone: "(54) 98359-1475",
      endereco_logradouro: "Rua Luiza Miranda Coelho",
      endereco_bairro: "Luciano Cavalcante",
      endereco_cep: "60811110",
      endereco_numero: "800",
    },
  ]);
};

exports.down = async function (knex) {
  return await knex("funcionario").del();
};
